<a href="https://colab.research.google.com/github/PNihalReddy/Data-Science-Practical-Files/blob/main/DS_CO1_HA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import numpy as np

In [17]:
a = np.arange(1, 21)
print("Original 1D array:")
print(a)
print("Shape:", a.shape)

Original 1D array:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Shape: (20,)


In [18]:
reshaped_a = a.reshape(4, 5)
print("\nReshaped 2D array (3x4):")
print(reshaped_a)
print("Shape:", reshaped_a.shape)


Reshaped 2D array (3x4):
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
Shape: (4, 5)


In [19]:
transposed_a = reshaped_a.T
print("\nTransposed array :")
print(transposed_a)
print("Shape:", transposed_a.shape)


Transposed array :
[[ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]
 [ 5 10 15 20]]
Shape: (5, 4)


In [20]:
import re

In [21]:
raw_data = [
    "  Hello World!! ",
    "hello world",
    "HELLO   WORLD",
    "Python Programming...",
    "python   programming",
    "  Data Science  ",
    "DATA SCIENCE!!",
    "",
    "   "
]
print("Original Data:")
for item in raw_data:
    print(repr(item))

Original Data:
'  Hello World!! '
'hello world'
'HELLO   WORLD'
'Python Programming...'
'python   programming'
'  Data Science  '
'DATA SCIENCE!!'
''
'   '


In [22]:
def clean_text(text):

    text = text.strip()

    text = text.lower()

    text = re.sub(r'[^\w\s]', '', text)

    text = re.sub(r'\s+', ' ', text)
    return text.strip()

In [23]:
cleaned_data = [clean_text(entry) for entry in raw_data]

cleaned_data = [entry for entry in cleaned_data if entry != ""]

print("\nCleaned Data (before removing duplicates):")
for item in cleaned_data:
    print(item)


Cleaned Data (before removing duplicates):
hello world
hello world
hello world
python programming
python programming
data science
data science


In [24]:
final_data = list(dict.fromkeys(cleaned_data))

print("\nFinal Cleaned & De-duplicated Data:")
for item in final_data:
    print(item)


Final Cleaned & De-duplicated Data:
hello world
python programming
data science
